### ISSUE TITLE
Send /toxic message as ephermal if it goes above threshold

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Dotsimus#101]
### MVP feature

- [x] Add in a logic to turn embed into ephermal if toxicity is equal or above 0.80 value, you can find the related part over here https://github.com/Microsoft-community/Dotsimus/blob/696288aa9abb25fb160267d82b3527401ea09ca8/src/features/commands/toxic.js#L33

## User story

1. User submits highly toxic message with /toxic command
2. User gets prompted with ephermal toxicity embed(the one that it has right now) and it has a message "Are you sure that you want to share this content? It might be seen as inappropriate by the moderation team."
3. Ephermal message has two buttons
One in red color which says "Send anyways" and one in grey which says "Don't send"

Click send anyways sends normal embed as expected, maybe it would be good to include some kind of message along with it to make people and mods aware that it was a conscious decision to send it, but I can't think of a good text for that right now.

Don't send just hides the buttons and leaves everything as is.

## TODO

- [x] Make toxicity embed ephermal if it's above or equal to 0.80 value

- [x] Include "Are you sure that you want to share this content? It might be seen as inappropriate by the moderation team." message if toxicity is above or equal to 0.80 value
- [x] Include buttons that do actions specified in the user story and disappears if toxicity is above or equal to 0.80 value

**Comment by Jasius** [comment]
Fixed in #110
